### ISSUE TITLE
auto logging is not working on docker 

### ISSUE THREAD

**Issue by pint12** [mzipay/Autologging#1] opened 2016-05-22 19:58 UTC
i am trying to use my python app on docker now i use there a packed called auto-logging which is actually using python logger

when i use this app inside a docker container it printout the sys prints but not the one generated by the logger

i have tried to define the following in the compose and it still not working stdin_open: True tty: True privileged: True cap_add: - "ALL" environment: - PYTHONUNBUFFERED=0

**Comment by mzipay** [comment] 2016-05-24 14:13
Thanks for the notice, pint12.

I have installed Docker locally and will attempt to reproduce and diagnose this evening. In the meantime, can I ask you to provide a bit more detail?

- Python implementation (e.g. CPython, PyPy) and version
- your Python logging configuration (e.g. your INI config file, or a code excerpt showing how your application calls logging.basicConfig, logging.config.dictConfig, or logging.config.fileConfig)

(If you are not specifying a logging configuration explicitly in your app, it might simply be that the root logger is suppressing log entries.)

**Comment by mzipay** [comment] 2016-05-25 02:45
Hi, pint12,

After playing around a bit with Docker, I believe that the problem you are experiencing is due to your application not having a logging configuration in place.

I was able to create a sample Docker image that demonstrates autologging.logged and autologging.traced:
https://hub.docker.com/r/mzipay/autologging-issue-1/

You can follow the instructions listed in the repo's description to try it out. You can find out more about how to configure Python's logging module here:
https://docs.python.org/library/logging.config.html

**Comment by mzipay** [comment] 2016-07-06 21:31
pint12, I am closing this issue because I haven't seen any feedback. The docker example I referenced works; I hope you are able to reference it to solve your issue.

**Closed by mzipay** 2016-07-06 21:31 UTC
Labels: question
